// event names
export const PLAYER_CHANGE_HP = "PLAYER_CHANGE_HP";
export const PLAYER_CHANGE_BOMB_COUNT = "PLAYER_CHANGE_BOMB_COUNT";
export const PLAYER_CHANGE_LEVEL = "PLAYER_CHANGE_LEVEL";
export const PLAYER_RESET_BOMB_COUNTDOWN = "PLAYER_RESET_BOMB_COUNTDOWN";
export const GAME_UPDATE_SCORE = "GAME_UPDATE_SCORE";
export const GAME_STATE_UPDATE = "GAME_STATE_UPDATE";
// localstorage keys
export const GAME_BEST_SCORE = "GAME_BEST_SCORE";
// Object pool keys
export const OBJECT_POOL_KEY_PREFIX = "OBJECT_POOL_KEY_";
export const OBJECT_POOL_KEY_ENEMY0 = "OBJECT_POOL_KEY_ENEMY0";
export const OBJECT_POOL_KEY_ENEMY1 = "OBJECT_POOL_KEY_ENEMY1";
export const OBJECT_POOL_KEY_ENEMY2 = "OBJECT_POOL_KEY_ENEMY2";
export const OBJECT_POOL_KEY_BULLET0 = "OBJECT_POOL_KEY_BULLET0";
export const OBJECT_POOL_KEY_BULLET1 = "OBJECT_POOL_KEY_BULLET1";
export const OBJECT_POOL_KEY_REWARD_BOMB = "OBJECT_POOL_KEY_REWARD_BOMB";
export const OBJECT_POOL_KEY_REWARD_DOUBLE_BULLET = "OBJECT_POOL_KEY_REWARD_DOUBLE_BULLET";
